language: ruby
rvm:
  - 2.1.1

before_script:
  - "cp config/database.sample.yml config/database.yml"
  - "psql -c 'create role eufaco SUPERUSER LOGIN;' postgres"
  - "psql -c 'create database eufaco_test;' -U eufaco postgres"
  - "bin/rake db:migrate RAILS_ENV=test"
  - "sh -e /etc/init.d/xvfb start"

env:
  - DISPLAY=:99.0

script:
  - "bundle exec rspec spec && bundle exec cucumber"

branches:
  only:
    - master
